// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: edpc.proto

package edpcrpc

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string               `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Fid         string               `protobuf:"bytes,2,opt,name=fid,proto3" json:"fid,omitempty"`
	Tevt        *timestamp.Timestamp `protobuf:"bytes,3,opt,name=tevt,proto3" json:"tevt,omitempty"`
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RequestHeader) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *RequestHeader) GetTevt() *timestamp.Timestamp {
	if x != nil {
		return x.Tevt
	}
	return nil
}

type ReplyHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Redirect string `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
}

func (x *ReplyHeader) Reset() {
	*x = ReplyHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyHeader) ProtoMessage() {}

func (x *ReplyHeader) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyHeader.ProtoReflect.Descriptor instead.
func (*ReplyHeader) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyHeader) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

type CommanderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr  *RequestHeader `protobuf:"bytes,1,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Cmdr string         `protobuf:"bytes,3,opt,name=cmdr,proto3" json:"cmdr,omitempty"`
}

func (x *CommanderRequest) Reset() {
	*x = CommanderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommanderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommanderRequest) ProtoMessage() {}

func (x *CommanderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommanderRequest.ProtoReflect.Descriptor instead.
func (*CommanderRequest) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{2}
}

func (x *CommanderRequest) GetHdr() *RequestHeader {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *CommanderRequest) GetCmdr() string {
	if x != nil {
		return x.Cmdr
	}
	return ""
}

type DockedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr    *RequestHeader `protobuf:"bytes,1,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Addr   uint64         `protobuf:"varint,2,opt,name=addr,proto3" json:"addr,omitempty"`
	System string         `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	Port   string         `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DockedRequest) Reset() {
	*x = DockedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockedRequest) ProtoMessage() {}

func (x *DockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockedRequest.ProtoReflect.Descriptor instead.
func (*DockedRequest) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{3}
}

func (x *DockedRequest) GetHdr() *RequestHeader {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *DockedRequest) GetAddr() uint64 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *DockedRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *DockedRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type TriggerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr      *ReplyHeader         `protobuf:"bytes,1,opt,name=hdr,proto3" json:"hdr,omitempty"`
	NewHints []*TriggerReply_Hint `protobuf:"bytes,2,rep,name=new_hints,json=newHints,proto3" json:"new_hints,omitempty"`
}

func (x *TriggerReply) Reset() {
	*x = TriggerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReply) ProtoMessage() {}

func (x *TriggerReply) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReply.ProtoReflect.Descriptor instead.
func (*TriggerReply) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerReply) GetHdr() *ReplyHeader {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *TriggerReply) GetNewHints() []*TriggerReply_Hint {
	if x != nil {
		return x.NewHints
	}
	return nil
}

type TriggerReply_Hint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Story int32 `protobuf:"varint,1,opt,name=story,proto3" json:"story,omitempty"`
	Hint  int32 `protobuf:"varint,2,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *TriggerReply_Hint) Reset() {
	*x = TriggerReply_Hint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerReply_Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReply_Hint) ProtoMessage() {}

func (x *TriggerReply_Hint) ProtoReflect() protoreflect.Message {
	mi := &file_edpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReply_Hint.ProtoReflect.Descriptor instead.
func (*TriggerReply_Hint) Descriptor() ([]byte, []int) {
	return file_edpc_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TriggerReply_Hint) GetStory() int32 {
	if x != nil {
		return x.Story
	}
	return 0
}

func (x *TriggerReply_Hint) GetHint() int32 {
	if x != nil {
		return x.Hint
	}
	return 0
}

var File_edpc_proto protoreflect.FileDescriptor

var file_edpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x64, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66,
	0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x65, 0x76, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x65,
	0x76, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x22, 0x48, 0x0a,
	0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x03, 0x68, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x03,
	0x68, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6d, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6d, 0x64, 0x72, 0x22, 0x71, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x68, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x03, 0x68, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x03, 0x68,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x03, 0x68, 0x64, 0x72, 0x12, 0x2f, 0x0a, 0x09, 0x6e,
	0x65, 0x77, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x48, 0x69,
	0x6e, 0x74, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x30, 0x0a, 0x04,
	0x48, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x32, 0x5e,
	0x0a, 0x06, 0x45, 0x44, 0x50, 0x43, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x12, 0x0e, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6d, 0x64,
	0x72, 0x56, 0x61, 0x73, 0x71, 0x75, 0x65, 0x73, 0x73, 0x2f, 0x65, 0x64, 0x70, 0x63, 0x2f, 0x65,
	0x64, 0x70, 0x63, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_edpc_proto_rawDescOnce sync.Once
	file_edpc_proto_rawDescData = file_edpc_proto_rawDesc
)

func file_edpc_proto_rawDescGZIP() []byte {
	file_edpc_proto_rawDescOnce.Do(func() {
		file_edpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_edpc_proto_rawDescData)
	})
	return file_edpc_proto_rawDescData
}

var file_edpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_edpc_proto_goTypes = []interface{}{
	(*RequestHeader)(nil),       // 0: RequestHeader
	(*ReplyHeader)(nil),         // 1: ReplyHeader
	(*CommanderRequest)(nil),    // 2: CommanderRequest
	(*DockedRequest)(nil),       // 3: DockedRequest
	(*TriggerReply)(nil),        // 4: TriggerReply
	(*TriggerReply_Hint)(nil),   // 5: TriggerReply.Hint
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_edpc_proto_depIdxs = []int32{
	6, // 0: RequestHeader.tevt:type_name -> google.protobuf.Timestamp
	0, // 1: CommanderRequest.hdr:type_name -> RequestHeader
	0, // 2: DockedRequest.hdr:type_name -> RequestHeader
	1, // 3: TriggerReply.hdr:type_name -> ReplyHeader
	5, // 4: TriggerReply.new_hints:type_name -> TriggerReply.Hint
	2, // 5: EDPCer.Commander:input_type -> CommanderRequest
	3, // 6: EDPCer.Docked:input_type -> DockedRequest
	1, // 7: EDPCer.Commander:output_type -> ReplyHeader
	1, // 8: EDPCer.Docked:output_type -> ReplyHeader
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_edpc_proto_init() }
func file_edpc_proto_init() {
	if File_edpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommanderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerReply_Hint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edpc_proto_goTypes,
		DependencyIndexes: file_edpc_proto_depIdxs,
		MessageInfos:      file_edpc_proto_msgTypes,
	}.Build()
	File_edpc_proto = out.File
	file_edpc_proto_rawDesc = nil
	file_edpc_proto_goTypes = nil
	file_edpc_proto_depIdxs = nil
}
